import Head from 'next/head';
import styles from 'src/styles/Home.module.css';
import { Footer }  from 'src/components/Footer';
import { Main } from 'src/components/Main';
import { Header } from 'src/components/Header';
import { useCallback, useEffect } from 'react';
import Link from 'next/link';

export default function Home() {
  const foo = 1 ;

  const handleClick = useCallback( (e) => {
    console.log(e.target.href)
    e.preventDefault();
    alert(foo);
  }, []);

  useEffect(() => {
    document.body.style.backgroundColor = "lightblue";
    return () => {
      document.body.style.backgroundColor = "";
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Link href="/about">
        <a  onClick={handleClick}>ボタン</a>
      </Link>
      
      <Main page="index" />
      <Footer />
    </div>
  )
}
